DELE/DELE/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('dashboard.urls')),
]

DELE/dashboard/urls.py
from django.urls import path
from .views import *

app_name = 'dashboard'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='dashboard/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('', HomeView.as_view(), name='list_tournaments'),  
    path('send-email/', send_email, name='send_email'),
    # path('create_tournament/', CreateTournament.as_view(), name='create_tournament'),  
    # path('tournament/<int:id>', View_Tournament.as_view(), name='view_tournament'),    
    # path('edit_tournament/<int:id>', EditTournament.as_view(), name='edit_tournament'),     
    # path('no_permission/', NoPermission.as_view(), name='no_permission'),    
    # path('delete_tournament/<int:id>', DeleteTournament.as_view(), name='delete_tournament'),      
    # path('participating_tournament/', ParticipatingTournaments.as_view(), name='participating_tournament'),  
    # path('index/', Index.as_view(), name='index'),
    # path('mytournaments/', MyTournaments.as_view(), name='mytournaments'),
    # path('tournament/<int:tournament_id>/participants/', Participants.as_view(), name='participants'),
    # path('user/profile/<int:user_id>', UserProfileView.as_view(), name='user_profile'),
    # path('user/profile/edit/', EditUserProfile.as_view(), name='edit_user_profile'),
]

DELE/dashboard/models.py
from django.db import models

# Create your models here.

DELE/dashboard/forms.py
from django import forms
# from .models import Tournament, UserProfile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _

# class TournamentForm(forms.ModelForm):
    
#     class Meta:
#         model = Tournament
#         exclude = ['organizer', 'status', 'participants']

class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput)

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
        
    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        # Remove help text for username
        self.fields['username'].help_text = ''
        # Remove help text for password1
        self.fields['password1'].help_text = ''
        # Remove help text for password2
        self.fields['password2'].help_text = ''

# class EditUserProfileForm(forms.ModelForm):
#     class Meta:
#         model = UserProfile
#         fields = ['bio', 'country', 'first_name', 'last_name']


# forms.py

DELE/dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.utils.http import urlencode
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import SignupForm, LoginForm
from django.core.mail import send_mail
from django.http import HttpResponse


# from .models import Tournament, UserProfile


class LoginView(View):

    template_name = 'dashboard/login.html'

    def get(self, request):
        form = LoginForm()
        return render(request, self.template_name, {'form' : form})

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('dashboard:list_tournaments')  
        return render(request, self.template_name, {'error': 'Invalid login credentials'})


class LogoutView(View):

    def get(self, request):
        logout(request)
        return redirect('dashboard:login') 


class SignupView(View):
    template_name = 'dashboard/signup.html'

    def get(self, request):
        form = SignupForm()
        return render(request, self.template_name, {'form': form})


    def post(self, request):
        form = SignupForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']

            if User.objects.filter(username=username).exists():
                messages.error(request, 'Username already exists. Please choose a different username.')
                return redirect('dashboard:signup')

            User.objects.create_user(username=username, password=password)
            messages.success(request, 'Account created successfully. You can now log in.')
            return redirect('dashboard:login')
        else:
            form = SignupForm()
            return redirect(request.path, {'form' : form, 'error':'invalid credentials'})

class HomeView(LoginRequiredMixin,View):

    template_name = 'dashboard/list_tournaments.html'
    login_url  = 'dashboard:login'

    def get(self, request): 
        return render(request, self.template_name, { 'title': 'home'})

def send_email(request):
    if request.method == 'POST':
        subject = 'notification module success'
        message = 'Congratulations! your notification module works.'
        from_email = 'xrt5996@gmail.com'  # Change this to your email address
        to_email = ['virtualprey@gmail.com']  # Change this to the recipient's email address
        send_mail(subject, message, from_email, to_email, fail_silently=False)
        return HttpResponse('Email sent successfully!')
    else:
        return render(request, 'dashboard/list_tournaments.html')  # Replace 'your_template.html' with the template containing your button




# class CreateTournament(LoginRequiredMixin,View):

#     template_name = 'tournaments/create_tournaments.html'
#     login_url  = 'tournaments:login'

#     def get(self, request):   
#         form = TournamentForm()
#         return render(request, self.template_name, {'form': form})

#     def post(self, request):
#         form = TournamentForm(request.POST, request.FILES)
#         if form.is_valid():
#             tournament = form.save(commit=False)
#             tournament.organizer = request.user
#             tournament.save()
#             return redirect('tournaments:list_tournaments')
#         error = "invalid form"
#         return redirect('tournaments:create_tournament', {'error':error})




# class View_Tournament( LoginRequiredMixin,View):

#     template_name = 'tournaments/view_tournament.html'
#     login_url  = 'tournaments:login'

#     def get(self, request, id):
#         tournament = get_object_or_404(Tournament, id=id)
#         user = request.user
#         is_participant = tournament.participants.filter(id=user.id).exists()
#         return render(request, self.template_name, {'tournament': tournament, 'is_participant': is_participant})

#     def post(self, request, id):
#         tournament = get_object_or_404(Tournament, id=id)
#         user = request.user
#         action = request.POST.get('action')

#         if action == 'join':
#             tournament.participants.add(user)
#         elif action == 'leave':
#             tournament.participants.remove(user)

#         return redirect('tournaments:list_tournaments')

# class EditTournament( UserPassesTestMixin,View):
    
#     template_name = 'tournaments/edit_tournament.html'
#     login_url  = 'tournaments:login'
    
#     def test_func(self):
#         tournament = get_object_or_404(Tournament, id=self.kwargs['id'])
#         return self.request.user == tournament.organizer
    
#     def handle_no_permission(self):
#         messages.error(self.request, "You don't have permission to edit this tournament.")
#         return redirect('tournaments:no_permission') 

#     def get(self, request, id):
#         tournament = get_object_or_404(Tournament, id=id)
#         form = TournamentForm(instance=tournament)
#         return render(request, self.template_name, {'form': form, 'tournament': tournament})

#     def post(self, request, id):
#         tournament = get_object_or_404(Tournament, id=id)
#         form = TournamentForm(request.POST, request.FILES , instance=tournament,)
#         if form.is_valid():
#             form.save()
#             return redirect('tournaments:view_tournament', id=id)
        
# class NoPermission(View):

#     template_name = 'tournaments/no_permission.html'

#     def get(self, request):
#         return render(request, self.template_name)
    
# class DeleteTournament(UserPassesTestMixin, View):
    
#     template_name = 'tournaments/delete_tournament.html'

#     def test_func(self):
#         tournament = get_object_or_404(Tournament, id=self.kwargs['id'])
#         return self.request.user == tournament.organizer
    
#     def handle_no_permission(self):
#         messages.error(self.request, "You don't have permission to edit this tournament.")
#         return redirect('tournaments:no_permission') 

#     def get(self, request, id):
#         tournament = get_object_or_404(Tournament, id=id)
#         return render(request, self.template_name, {'tournament': tournament})

#     def post(self, request, id):
#         tournament = get_object_or_404(Tournament, id=id)
#         tournament.delete()
#         return redirect('tournaments:list_tournaments')
    
# class ParticipatingTournaments(LoginRequiredMixin,View):

#     template_name = 'tournaments/participating_tournaments.html'
#     login_url  = 'tournaments:login'

#     def get(self, request):

#         tournaments = Tournament.objects.filter(participants=request.user)
#         participants = Tournament.participants

#         context = {'tournaments': tournaments, 'participants':participants}
#         return render(request, self.template_name, context)
    
# class Index(View):
#     template_name = 'tournaments/index.html'

#     def get(self, request):
#         return render(request, self.template_name)
    


# class MyTournaments(LoginRequiredMixin, View):
#     template_name = 'tournaments/mytournaments.html'
#     login_url = 'tournament:login'

#     def get(self, request):
#         tournaments = Tournament.objects.filter(organizer=request.user)
#         return render(request, self.template_name, {'tournaments': tournaments})

# class Participants(LoginRequiredMixin, View):

#     template_name = 'tournaments/participants.html'
#     login_url = 'tournament:login'

#     def get(self, request, tournament_id):
#         tournament = get_object_or_404(Tournament, id=tournament_id)
#         return render(request, 'tournaments/participants.html', {'tournament': tournament})
    
# class UserProfileView(LoginRequiredMixin, View):
#     template_name = 'user_profile.html'

#     def get(self, request, *args, **kwargs):
#         user_profile = UserProfile.objects.get(user=request.user)
#         return render(request, self.template_name, {'user_profile': user_profile})

# class EditUserProfile(UserPassesTestMixin, View):
#     model = UserProfile
#     form_class = UserProfile
#     template_name = 'edit_user_profile.html'
#     success_url = reverse_lazy('user_profile')

#     def get_object(self, queryset=None):
#         return self.model.objects.get(user=self.request.user)

DELE/dashboard/templates/dashboard/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title></title>
  <meta content="" name="description">
  <meta content="" name="keywords">
  {% load static %}

  <!-- Favicons -->
  <link href="{% static '/img/favicon.png' %} " rel="icon">
  <link href="{% static '/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;500&family=Inter:wght@400;500&family=Playfair+Display:ital,wght@0,400;0,700;1,400;1,700&display=swap' %}" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static '/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static '/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static '/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <link href="{% static '/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static '/vendor/aos/aos.css' %}" rel="stylesheet">

  <!-- Template Main CSS Files -->
  <link href="{% static '/css/variables.css' %}" rel="stylesheet">
  <link href="{% static '/css/main.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: ZenBlog
  * Updated: Sep 18 2023 with Bootstrap v5.3.2
  * Template URL:'https://bo"tstrapmade.com/zenblo"-bootstrap-blog-template/
  * Author: BootstrapMade.com
  * License: https:///bootstrapmade.com/license/
  ======================================================== -->
</head>

<body style="">
  <!-- ======= Header ======= -->
  <header id="header" class="header d-flex align-items-center mb-4">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <a href="{% url 'dashboard:list_tournaments' %}" class="logo d-flex align-items-center">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="{% static '/img/logo.png" alt=""> -->
        <h1>GGgulag</h1>
      </a>

      <nav id="navbar" class="navbar">
        <ul>
            <ul class="footer-links list-unstyled">
                <li><a href="{% url 'dashboard:list_tournaments' %}"> Home</a></li>
                <li><a href="{% url 'dashboard:logout' %}">logout</a></li>
              </ul>
      </nav><!-- .navbar -->

      <div class=>
        <a href="#" class="mx-2"><span class="bi-facebook"></span></a>
        <a href="#" class="mx-2"><span class="bi-twitter"></span></a>
        <a href="#" class="mx-2"><span class="bi-instagram"></span></a>

        <a href="#" class="mx-2 js-search-open"><span class="bi-search"></span></a>
        <i class="bi bi-list mobile-nav-toggle"></i>

        <!-- ======= Search Form ======= -->
        <div class="search-form-wrap js-search-form-wrap">
          <form action="search-result.html" class="search-form">
            <span class="icon bi-search"></span>
            <input type="text" placeholder="Search" class="form-control">
            <button class="btn js-search-close"><span class="bi-x"></span></button>
          </form>
        </div><!-- End Search Form -->

      </div>

    </div>

  </header><!-- End Header -->
    {% block content %}
    {% endblock %}
<footer id="footer" class="footer">

    <div class="footer-content">
      <div class="container">

        <div class="row g-5">
          <div class="col-lg-4">
            <h3 class="footer-heading">About GGgulag</h3>
            <p>Ggulag is a gaming tournament platform offering users the thrill of competition, enabling easy creation, participation, and management of tournaments in various games.</p>
            <p><a href="about.html" class="footer-link-more">Learn More</a></p>

          </div>
          <div class="col-6 col-lg-2">
            <h3 class="footer-heading">Navigation</h3>
            <ul class="footer-links list-unstyled">
              <li><a href="{% url 'dashboard:list_tournaments' %}"><i class="bi bi-chevron-right"></i> Home</a></li>
              <li><a href="{% url 'dashboard:logout' %}"><i class="bi bi-chevron-right"></i>logout</a></li>
            </ul>
          </div>
          <div class="col-6 col-lg-2">
            <h3 class="footer-heading">Categories</h3>
            <ul class="footer-links list-unstyled">
              <li><a href="category.html"><i class="bi bi-chevron-right"></i> Business</a></li>
              <li><a href="category.html"><i class="bi bi-chevron-right"></i> Culture</a></li>
              <li><a href="category.html"><i class="bi bi-chevron-right"></i> Sport</a></li>
              <li><a href="category.html"><i class="bi bi-chevron-right"></i> Food</a></li>
              <li><a href="category.html"><i class="bi bi-chevron-right"></i> Politics</a></li>
              <li><a href="category.html"><i class="bi bi-chevron-right"></i> Celebrity</a></li>
              <li><a href="category.html"><i class="bi bi-chevron-right"></i> Startups</a></li>
              <li><a href="category.html"><i class="bi bi-chevron-right"></i> Travel</a></li>

            </ul>
          </div>

          <div class="col-lg-4">
            <h3 class="footer-heading">Recent Posts</h3>

            <ul class="footer-links footer-blog-entry list-unstyled">
              <li>
                <a href="single-post.html" class="d-flex align-items-center">
                  <img src="{% static '/img/post-sq-1.jpg' %}" alt="" class="img-fluid me-3">
                  <div>
                    <div class="post-meta d-block"><span class="date">Culture</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '22</span></div>
                    <span>5 Great Startup Tips for Female Founders</span>
                  </div>
                </a>
              </li>

              <li>
                <a href="single-post.html" class="d-flex align-items-center">
                  <img src="{% static '/img/post-sq-2.jpg' %}" alt="" class="img-fluid me-3">
                  <div>
                    <div class="post-meta d-block"><span class="date">Culture</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '22</span></div>
                    <span>What is the son of Football Coach John Gruden, Deuce Gruden doing Now?</span>
                  </div>
                </a>
              </li>

              <li>
                <a href="single-post.html" class="d-flex align-items-center">
                  <img src="{% static '/img/post-sq-3.jpg' %}" alt="" class="img-fluid me-3">
                  <div>
                    <div class="post-meta d-block"><span class="date">Culture</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '22</span></div>
                    <span>Life Insurance And Pregnancy: A Working Mom’s Guide</span>
                  </div>
                </a>
              </li>

              <li>
                <a href="single-post.html" class="d-flex align-items-center">
                  <img src="{% static '/img/post-sq-4.jpg' %}" alt="" class="img-fluid me-3">
                  <div>
                    <div class="post-meta d-block"><span class="date">Culture</span> <span class="mx-1">&bullet;</span> <span>Jul 5th '22</span></div>
                    <span>How to Avoid Distraction and Stay Focused During Video Calls?</span>
                  </div>
                </a>
              </li>

            </ul>

          </div>
        </div>
      </div>
    </div>

    <div class="footer-legal">
      <div class="container">

        <div class="row justify-content-between">
          <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
            <div class="copyright">
              © Copyright <strong><span>GGgulag</span></strong>. All Rights Reserved
            </div>

            <div class="credits">
              <!-- All the links in the footer should remain intact. -->
              <!-- You can delete the links only if you purchased the pro version. -->
              <!-- Licensing information: https://bootstrapmade.com/license/ -->
              <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/herobiz-bootstrap-business-template/ -->
              Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
            </div>

          </div>

          <div class="col-md-6">
            <div class="social-links mb-3 mb-lg-0 text-center text-md-end">
              <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
              <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
              <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
              <a href="#" class="google-plus"><i class="bi bi-skype"></i></a>
              <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
            </div>

          </div>

        </div>

      </div>
    </div>

  </footer>

  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static '/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="{% static '/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="{% static '/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="{% static '/vendor/aos/aos.js"></script>
  <script src="{% static '/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="{% static '/js/main.js"></script>

</body>

</html>

DELE/dashboard/templates/dashboard/create_tournaments.html
{% extends 'tournaments/base.html' %}
{% block content %}
<head>
    <style>
.content{
    width: 30%;
    margin: auto;
}
input {
    font-size: 16px;
    line-height: 28px;
    margin-bottom: 2rem;
    padding: 8px 16px;
    width: 100%;
    min-height: 44px;
    border: unset;
    border-radius: 4px;
    outline-color: rgb(84 105 212 / 0.5);
    background-color: rgb(255, 255, 255);
    box-shadow: rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
                rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
                rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
                rgba(60, 66, 87, 0.16) 0px 0px 0px 1px, 
                rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
                rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
                rgba(0, 0, 0, 0) 0px 0px 0px 0px;
}

input[type="submit"] {
    background-color: rgb(0, 1, 7);
    box-shadow: rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
                rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
                rgba(0, 0, 0, 0.12) 0px 1px 1px 0px, 
                rgb(84, 105, 212) 0px 0px 0px 1px, 
                rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
                rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
                rgba(60, 66, 87, 0.08) 0px 2px 5px 0px;
    color: #fff;
    font-weight: 600;
    cursor: pointer;
}

    </style>

</head>

{% if error %}
<div class="alert alert-danger">
    {{error}}
</div>
{% endif %}
<div class="content">
<h1 class="text-center mb-3 ">Create your tournament here!</h1>
<form class="form-group stripe-login" class="mb-4" action="{% url 'tournaments:create_tournament' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="create tournament">
</form></div>
{% endblock %}

DELE/dashboard/templates/dashboard/delete_tournament.html
{% extends 'tournaments/base.html' %}

{% block content %}
<div class="container text-center py-5">
  <h1>Delete Tournament</h1>
  
  <h4>Are you sure you want to delete the tournament "{{ tournament.title }}"?</h4>
  
  <form method="post" action="{% url 'tournaments:delete_tournament' tournament.id %}">
    {% csrf_token %}
    <button class="mr-2 btn btn-danger" type="submit">Delete</button>
    <button class="btn btn-primary"><a class='text-white' href="{% url 'tournaments:view_tournament' tournament.id %}">Cancel</a></button>
  </form>
</div>
{% endblock %}

DELE/dashboard/templates/dashboard/edit_tournament.html
{% extends 'tournaments/base.html' %}

{% block content %}
{% block header %}
{% endblock %}
<head>
  <style>
.content{
  width: 30%;
  margin: auto;
}
input {
  font-size: 16px;
  line-height: 28px;
  margin-bottom: 2rem;
  padding: 8px 16px;
  width: 100%;
  min-height: 44px;
  border: unset;
  border-radius: 4px;
  outline-color: rgb(84 105 212 / 0.5);
  background-color: rgb(255, 255, 255);
  box-shadow: rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
              rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
              rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
              rgba(60, 66, 87, 0.16) 0px 0px 0px 1px, 
              rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
              rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
              rgba(0, 0, 0, 0) 0px 0px 0px 0px;
}

input[type="submit"] {
  background-color: rgb(0, 1, 7);
  box-shadow: rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
              rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
              rgba(0, 0, 0, 0.12) 0px 1px 1px 0px, 
              rgb(84, 105, 212) 0px 0px 0px 1px, 
              rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
              rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
              rgba(60, 66, 87, 0.08) 0px 2px 5px 0px;
  color: #fff;
  font-weight: 600;
  cursor: pointer;
}

  </style>

</head>
<div class="content">
  <h1 class="text-center my-3">Edit Tournament</h1>
  <form method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update tournament">
  </form>
</div>
{% endblock %}
<!-- <div class="form">
  <form action="{% url 'tournaments:edit_tournament' %}" method="post" role="form" class="php-email-form">
    <div class="row">
      <div class="form-group col-md-6">
        {{ f }}
      </div>
      <div class="form-group col-md-6">
        <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" required>
      </div>
    </div>
    <div class="form-group">
      <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required>
    </div>
    <div class="form-group">
      <textarea class="form-control" name="message" rows="5" placeholder="Message" required></textarea>
    </div>
    <div class="my-3">
      <div class="loading">Loading</div>
      <div class="error-message"></div>
      <div class="sent-message">Your message has been sent. Thank you!</div>
    </div>
    <div class="text-center"><button type="submit">Save Changes</button></div>
  </form>
</div>End Contact Form -->

DELE/dashboard/templates/dashboard/edit_user_profile.html
<!-- tournaments/templates/tournaments/user/edit_user_profile.html -->
{% extends 'tournaments/base.html' %}
{% block content %}
  <h2>Edit User Profile</h2>
  <form method="post" action="{% url 'tournaments:edit_user_profile' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save Changes</button>
  </form>
  <a href="{% url 'tournaments:user_profile ' %}">Cancel</a>
{% endblock %}

DELE/dashboard/templates/dashboard/list_tournaments.html
{% extends 'dashboard/base.html' %}
{% block content %}
{% load static %}
<div class="text-center">
    <h1>Welcome to GGgulag Tournaments</h1>
    <p>Find a tornament tot join down below!</p>
    <form action="{% url 'dashboard:send_email' %}" method="post">
        {% csrf_token %}
        <button type="submit">Send Email</button>
    </form>
</div>
    {% if tournaments %}
    <div class=" row"> 

    {% for tournament in tournaments %}
    <!-- <div style="padding: 2rem;" class="container-fluid container-xl d-flex flex-column  justify-content-between">
        <a href="{% url 'tournaments:view_tournament' id=tournament.id %}">
        <h2>{{ tournament.title }}by {{ tournament.organizer.username }}</h2>
        <p></p>
        <p>{{ tournament.deadline }}</p>
        <p>{{ tournament.country_restriction }}</p>
        <p>{{ tournament.prize_pool }}</p>
        <p>{{ tournament.registration_fee }}</p></a>
    </div> -->
    <div class="col-md-4 col-sd-2">
    <div class="card p-3" style="width: 25rem; margin: 2rem 0;">

        {% if tournament.image %}
            <img src="media/{{ tournament.image }}" class="card-img-top img-fluid"  alt="{{ tournament.name }} Image">
        {% else %}
            <img class="card-img-top" src="{% static 'img/pexels-pixabay-260024.jpg' %}" alt="Card image cap">
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{ tournament.title }}</h5>
          <p class="card-text">{{ tournament.game }}</p>
          <a href="{% url 'dashboard:view_tournament' id=tournament.id %}" class="btn btn-primary">View tournament</a>
        </div>
      </div></div>
    {% endfor %}
</div>
    {% else %}
        non available
    {% endif %}
{% endblock %} 

DELE/dashboard/templates/dashboard/no_permission.html
{% extends 'tournaments/base.html' %}
{% block content %}

<p>you are a sneaky one aren't you</p>
<p>Sorry but only the owner can update the tournament</p>
<a href="{% url 'tournaments:list_tournaments' %}">tournaments</a></p>

{% endblock %}